name       : kfind
version    : 22.04.0
release    : 18
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.0/src/kfind-22.04.0.tar.xz : 5133cad0be64fb3fc3f9666b01b4cff8141016f31c244ed39a3e21fc298b6935
homepage   : https://www.kde.org/applications/utilities/kfind
license    : GPL-2.0-or-later
component  : system.utils
summary    : Find Files/Folders
description: |
    KFind allows you to search for directories and files
builddeps  :
    - karchive-devel
    - kdoctools-devel
    - kfilemetadata-devel
    - kio-devel
    - ktextwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove HTML docs
    rm -rv $installdir/usr/share/doc
