name       : kfind
version    : 21.08.1
release    : 12
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.1/src/kfind-21.08.1.tar.xz : ae8c19d207dd1e154f92676ae52ff1b4ddac78cb72157552d094db9f178d7534
homepage   : https://www.kde.org/applications/utilities/kfind
license    : GPL-2.0-or-later
component  : system.utils
summary    : Find Files/Folders
description: |
    KFind allows you to search for directories and files
builddeps  :
    - karchive-devel
    - kdoctools-devel
    - kfilemetadata-devel
    - kio-devel
    - ktextwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove HTML docs
    rm -rv $installdir/usr/share/doc
