name       : kfind
version    : 20.12.3
release    : 6
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.3/src/kfind-20.12.3.tar.xz : e6f608fcd717021bc2f4c69def81f18361c05abb72503deb268d219fb8a6f167
homepage   : https://www.kde.org/applications/utilities/kfind
license    : GPL-2.0-or-later
component  : system.utils
summary    : Find Files/Folders
description: |
    KFind allows you to search for directories and files
builddeps  :
    - karchive-devel
    - kdoctools-devel
    - kfilemetadata-devel
    - kio-devel
    - ktextwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove HTML docs
    rm -rv $installdir/usr/share/doc
