name       : kfind
version    : 22.04.2
release    : 20
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.2/src/kfind-22.04.2.tar.xz : e9376ff9fe03e2618896fa1bcf99e3ba7c0585ab7396528940204c156cdacaae
homepage   : https://www.kde.org/applications/utilities/kfind
license    : GPL-2.0-or-later
component  : system.utils
summary    : Find Files/Folders
description: |
    KFind allows you to search for directories and files
builddeps  :
    - karchive-devel
    - kdoctools-devel
    - kfilemetadata-devel
    - kio-devel
    - ktextwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove HTML docs
    rm -rv $installdir/usr/share/doc
