name       : kfind
version    : 22.12.1
release    : 23
source     :
    - https://cdn.download.kde.org/stable/release-service/22.12.1/src/kfind-22.12.1.tar.xz : 8a3af986212c116ca4d47b6d6f4c8af3654effd3615286eac0a61de9364e28d2
homepage   : https://www.kde.org/applications/utilities/kfind
license    : GPL-2.0-or-later
component  : system.utils
summary    : Find Files/Folders
description: |
    KFind allows you to search for directories and files
builddeps  :
    - karchive-devel
    - kdoctools-devel
    - kfilemetadata-devel
    - kio-devel
    - ktextwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove HTML docs
    rm -rv $installdir/usr/share/doc
