name       : kfind
version    : 21.08.0
release    : 11
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.0/src/kfind-21.08.0.tar.xz : 8f0a1609f2d6be32e29cb2c427480e05890e3dfba56a25510df337a79d304461
homepage   : https://www.kde.org/applications/utilities/kfind
license    : GPL-2.0-or-later
component  : system.utils
summary    : Find Files/Folders
description: |
    KFind allows you to search for directories and files
builddeps  :
    - karchive-devel
    - kdoctools-devel
    - kfilemetadata-devel
    - kio-devel
    - ktextwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove HTML docs
    rm -rv $installdir/usr/share/doc
